source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CoolnessPod_Example', :exclusive => true do
  pod 'CoolnessPod', :path => '../'
end

target 'CoolnessPod_Tests', :exclusive => true do
  pod 'CoolnessPod', :path => '../'

  
end
